### ISSUE TITLE
UDP connection to a WLED instance [Feature Request]

### ISSUE THREAD

**Issue by m00x-pixel** [cp2004/OctoPrint-WLED#1]
Maybe it can be possible to work with the WLED API from Aircookie via UDP wireless connection.
(ESP8266/ESP32 with connected LEDs)

So you can can have an small printer status light within the living room and see the state without going to the printer in the other room.

**Comment by ejdprops** [comment]
Feel free to reach out to me.  I managed to quickly link my Octoprint to my WLED using events in the Octoprint config file and sending an http request to my WLED based on Octoprint requests. It was super easy and I’m a total noob when it comes to Octoprint and RPi

**Comment by cp2004** [comment]
That's pretty much what I'm going to try and do, making this plugin but integrated nicely. Don't see much point in using UDP or MQTT, was just going to hit the http API connected to some events with a nice settings page.

I looked into using the home assistant WLED library and was in contact with its author, but it might be a little difficult to 'just do' since it is written to be async. Working on it between large releases on my other plugins so it might take a while.

**Comment by cp2004** [comment]
I set myself a goal of creating this plugin in 2020, and with just hours to go I am going to consider my goal met 😄 

I've just pushed my latest work. The current features of this plugin are event-reactive setting of WLED effects. It fully supports per-segment control, so you should be able to create some cool things. So, it is technically 'fully working'!

The UI takes a little getting used to, but I hope that with a few minor improvements & bug fixes it can become more streamlined. There's a couple of different states that need more work, and some better error messages (they're handled in the backend, just silently). I also want to implement discovery of WLED devices before it goes out to the plugin repository.

At this point, I still don't recommend installing it, since it is under *rapid* development and I might end up breaking everything before putting it back together again later.

Just thought I'd provide a small update, so that you know this request has not been forgotten about and is in fact under very active work!

**Comment by m00x-pixel** [comment]
Thank for the update. It sounds really good.

**Comment by cp2004** [comment]
Current target for release on the repository: 11th March. Aiming for earlier than that, but that is the absolute goal. It **will** be done by then. If I write it down, then I can't let it slide... *hopefully*

**Comment by cp2004** [comment]
The plugin is on it's way to the plugin repository 🚀

**Comment by cp2004** [comment]
Thanks for the patience here, it took a little longer than I expected due to other plugins and work elsewhere, but I made it 🙂 

Now just to prepare for a wave of users... Enjoy the plugin 🥳
