### ISSUE TITLE
Where is zero?

### ISSUE THREAD

**Issue by Piti31** [cp2004/OctoPrint-WLED#98]
Define wich LED is 12 o clock.

I have a clock with WLED and LED 0 is on 6 o clock.  60 LED all over all, so its LED 30 the 12 o clock mark. I can define it in WLED.
Octo Print WLED starts at LED 0, no possibility to define where it should start. 
Sorry for my broken english.

Thanks, Frank

**Comment by cp2004** [comment]
Sorry, somehow I forgot to reply here - it could have come through while I was away.

I understand the issue here, that you would like the effects to start at a different place than just the start of the strip. But, I don't control how the effects run on WLED from this plugin. I just tell it 'run rainbow effect' or 'set percentage to 50' for the progress. So I think this would be better done in WLED itself, otherwise I will have to reduce a lot of the functionality of this plugin so that the effects are all manually run by the plugin.

**Comment by Piti31** [comment]
Many thanks for your answer.

I love your plugin, no matter where it starts. :-)

**Comment by cp2004** [comment]
Since I don't think this is actually possible going through WLED's API, I'm going to close it. Whatever settings you've applied in WLED should work for this plugin's control as well, but I'm not sure of how the code there really works.
